name: Build-Tetorisu

on: push

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: choco search pkgname raylib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tetorisu-windows
          path: build/tetorisu.exe