name: Build-Tetorisu

on: push

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          choco install cmake git -y
          
      - name: Install raylib via vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          bootstrap-vcpkg.bat
          vcpkg integrate install
          vcpkg install raylib

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tetorisu-windows
          path: build/tetorisu.exe